# Generated by Django 5.0.7 on 2024-09-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_company_equipment'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
