# Generated by Django 5.0.7 on 2024-09-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_company_equipment_equipment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_price',
        ),
    ]
