# Generated by Django 5.0.7 on 2024-09-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_price'),
        ('equipment', '0003_remove_equipment_company_and_more'),
    ]

    operations = [
    ]
