import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { getServerSession } from "next-auth";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/app/Navbar"
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <AuthProvider>
              <Navbar />
              <Toaster/>
              {children}
            </AuthProvider>
          </div>
      </body>
    </html>
  );
}