# Generated by Django 5.0.7 on 2024-08-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_company_rep',
            new_name='is_company_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
