# Generated by Django 5.0.7 on 2024-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_account_is_email_verified_alter_account_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
