# Generated by Django 5.0.7 on 2024-09-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='name',
        ),
    ]
