# Generated by Django 5.0.7 on 2024-09-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='reservation',
            new_name='reserved_by',
        ),
    ]
