# Generated by Django 5.0.7 on 2024-09-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_remove_pickupslot_reserved_equipment_and_more'),
        ('complaints', '0002_rename_reservation_complaint_reserved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.comment')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_complaint', to='complaints.comment')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coplaint_slog', to='companies.pickupslot')),
            ],
        ),
    ]
