# Generated by Django 5.0.7 on 2024-09-12 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_usercomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaint',
            name='admin_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.comment'),
        ),
    ]
