# Generated by Django 5.0.7 on 2024-09-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='points_per_penalty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='points_per_pick',
            field=models.IntegerField(default=1),
        ),
    ]
