# Generated by Django 5.0.7 on 2024-08-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companie_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
