# Generated by Django 5.0.7 on 2024-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_delete_companie"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, related_name="equipment_list", to="equipment.equipment"
            ),
        ),
    ]
