# Generated by Django 5.0.7 on 2024-09-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_pickupslot_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='equipment',
        ),
    ]
