# Generated by Django 5.0.7 on 2024-08-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_pickupslot_is_expired"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="equipment",
        ),
        migrations.CreateModel(
            name="CompanyEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_equipments",
                        to="companies.company",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "equipment")},
            },
        ),
    ]
