# Generated by Django 5.0.7 on 2024-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_remove_company_equipment_companyequipment"),
        ("equipment", "0002_equipment_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business_hours",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="pickupslot",
            name="reserved_equipment",
            field=models.ManyToManyField(blank=True, to="equipment.equipment"),
        ),
    ]
