# Generated by Django 5.0.7 on 2024-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_company_equipment'),
        ('equipment', '0003_remove_equipment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment_list', to='equipment.equipment'),
        ),
    ]
