# Generated by Django 5.0.7 on 2024-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_company_business_hours_pickupslot_reserved_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickupslot",
            name="reserved_equipment",
            field=models.ManyToManyField(blank=True, to="companies.companyequipment"),
        ),
    ]
