# Generated by Django 5.0.7 on 2024-09-04 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_pickupslot_is_picked_up"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickupslot",
            name="is_reserved",
        ),
        migrations.AddField(
            model_name="pickupslot",
            name="reserved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
