# Generated by Django 5.0.7 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_remove_pickupslot_is_reserved_pickupslot_reserved_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickupslot",
            name="reserved_equipment",
        ),
        migrations.AddField(
            model_name="pickupslot",
            name="reserved_equipment",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
