# Generated by Django 5.0.7 on 2024-09-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_equipment'),
        ('companies', '0013_remove_pickupslot_reserved_equipment_and_more'),
    ]

    operations = [
    ]
