# Generated by Django 5.0.7 on 2024-08-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company"),
        ("profiles", "0004_systemadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companieadministrator",
            name="companie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="companies.company"
            ),
        ),
    ]
