# Generated by Django 5.0.7 on 2024-08-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_companieadministrator_companie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companieadministrator",
            old_name="companie",
            new_name="company",
        ),
    ]
