# Generated by Django 5.0.4 on 2024-08-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_equipment"),
        ("profiles", "0007_rename_companieadministrator_companyadministrator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyadministrator",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="administrators",
                to="companies.company",
            ),
        ),
    ]
