# Generated by Django 5.0.7 on 2024-09-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_companyadministrator_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadministrator',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
