# Generated by Django 5.0.7 on 2024-09-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_companyadministrator_is_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
